[tool.poetry]
name = "relativisticpy"
version = "1.1.2"
description = "A General Relativity package to solve symbolic General Relativistic equations."
authors = ["Ashley Cottrell"]

[build-system]
requires = ["setuptools>=40.8.0", "wheel", "sympy"]
build-backend = "setuptools.build_meta"

[tool.poetry.dependencies]
sympy = "^1.12"
